// GRAIL Card Catalog v3 — Official Topps 2025-26 NBA
// Sources: Official Topps PDFs, Checklist Insider, Beckett
// 9 products | 231 subsets | 1,616 parallel tiers | 5,452 cards
// Player names normalized (Topps typos corrected)
// Parallel numbering cross-referenced against all 3 sources
//
// Subset types: base, insert, autograph, relic, autograph_relic
// Tier format: "Name" (unnumbered) or ["Name", printRun] (numbered)

export const CARD_CATALOG: Record<string, {
  fullName: string; season: string; sortOrder: number;
  subsets: Array<{
    name: string; type: string; cardCount: number;
    tiers: Array<string | [string, number]>;
  }>;
}> = {
  "Topps Flagship": {
    fullName: "2025-26 Topps Flagship",
    season: "2025-26",
    sortOrder: 0,
    subsets: [
      { name: "BASE CARDS I", type: "base", cardCount: 261, tiers: ["Base", "Rainbow Foilboard", "Foilfractor", "Holo Foil", "Sand Glitter", "Green", "Orange", "Victory", ["Gold", 2025], ["Platinum", 1], ["Black", 1], "Rainbow", "Blue Rainbow", "Green Rainbow", "Purple Rainbow", "Gold Rainbow", "Orange Rainbow", "Red Rainbow", "Black Rainbow", "Basketball", "Basketball Pink", "Basketball Red", "Basketball Gold", "Basketball Black", "First Card", "Wood", "Surge", "Flash Drop", "Doorbuster", "Cart Load", "Blackout", "Diamante"] },
      { name: "BASE CARDS I GOLDEN MIRROR IMAGE VARIATION", type: "base", cardCount: 260, tiers: ["Base", "Rainbow Foilboard", "Foilfractor", "Holo Foil", "Sand Glitter", "Green", "Orange", "Victory", ["Gold", 2025], ["Platinum", 1], ["Black", 1], "Rainbow", "Blue Rainbow", "Green Rainbow", "Purple Rainbow", "Gold Rainbow", "Orange Rainbow", "Red Rainbow", "Black Rainbow", "Basketball", "Basketball Pink", "Basketball Red", "Basketball Gold", "Basketball Black", "First Card", "Wood", "Surge", "Flash Drop", "Doorbuster", "Cart Load", "Blackout", "Diamante"] },
      { name: "BASE CARDS I CLEAR VARIATION", type: "base", cardCount: 260, tiers: ["Base", "Rainbow Foilboard", "Foilfractor", "Holo Foil", "Sand Glitter", "Green", "Orange", "Victory", ["Gold", 2025], ["Platinum", 1], ["Black", 1], "Rainbow", "Blue Rainbow", "Green Rainbow", "Purple Rainbow", "Gold Rainbow", "Orange Rainbow", "Red Rainbow", "Black Rainbow", "Basketball", "Basketball Pink", "Basketball Red", "Basketball Gold", "Basketball Black", "First Card", "Wood", "Surge", "Flash Drop", "Doorbuster", "Cart Load", "Blackout", "Diamante"] },
      { name: "COMBO CARDS CLEAR VARIATION", type: "base", cardCount: 29, tiers: ["Base", "Rainbow Foilboard", "Foilfractor", "Holo Foil", "Sand Glitter", "Green", "Orange", "Victory", ["Gold", 2025], ["Platinum", 1], ["Black", 1], "Rainbow", "Blue Rainbow", "Green Rainbow", "Purple Rainbow", "Gold Rainbow", "Orange Rainbow", "Red Rainbow", "Black Rainbow", "Basketball", "Basketball Pink", "Basketball Red", "Basketball Gold", "Basketball Black", "First Card", "Wood", "Surge", "Flash Drop", "Doorbuster", "Cart Load", "Blackout", "Diamante"] },
      { name: "BASE CARDS I TEAM COLOR BORDER VARIATION", type: "base", cardCount: 94, tiers: ["Base", "Rainbow Foilboard", "Foilfractor", "Holo Foil", "Sand Glitter", "Green", "Orange", "Victory", ["Gold", 2025], ["Platinum", 1], ["Black", 1], "Rainbow", "Blue Rainbow", "Green Rainbow", "Purple Rainbow", "Gold Rainbow", "Orange Rainbow", "Red Rainbow", "Black Rainbow", "Basketball", "Basketball Pink", "Basketball Red", "Basketball Gold", "Basketball Black", "First Card", "Wood", "Surge", "Flash Drop", "Doorbuster", "Cart Load", "Blackout", "Diamante"] },
      { name: "BASE CARDS II TEAM COLOR BORDER VARIATION", type: "base", cardCount: 98, tiers: ["Base", "Rainbow Foilboard", "Foilfractor", "Holo Foil", "Sand Glitter", "Green", "Orange", "Victory", ["Gold", 2025], ["Platinum", 1], ["Black", 1], "Rainbow", "Blue Rainbow", "Green Rainbow", "Purple Rainbow", "Gold Rainbow", "Orange Rainbow", "Red Rainbow", "Black Rainbow", "Basketball", "Basketball Pink", "Basketball Red", "Basketball Gold", "Basketball Black", "First Card", "Wood", "Surge", "Flash Drop", "Doorbuster", "Cart Load", "Blackout", "Diamante"] },
      { name: "BASE CARDS III TEAM COLOR BORDER VARIATION", type: "base", cardCount: 68, tiers: ["Base", "Rainbow Foilboard", "Foilfractor", "Holo Foil", "Sand Glitter", "Green", "Orange", "Victory", ["Gold", 2025], ["Platinum", 1], ["Black", 1], "Rainbow", "Blue Rainbow", "Green Rainbow", "Purple Rainbow", "Gold Rainbow", "Orange Rainbow", "Red Rainbow", "Black Rainbow", "Basketball", "Basketball Pink", "Basketball Red", "Basketball Gold", "Basketball Black", "First Card", "Wood", "Surge", "Flash Drop", "Doorbuster", "Cart Load", "Blackout", "Diamante"] },
      { name: "COMBO CARDS TEAM COLOR BORDER VARIATION", type: "base", cardCount: 29, tiers: ["Base", "Rainbow Foilboard", "Foilfractor", "Holo Foil", "Sand Glitter", "Green", "Orange", "Victory", ["Gold", 2025], ["Platinum", 1], ["Black", 1], "Rainbow", "Blue Rainbow", "Green Rainbow", "Purple Rainbow", "Gold Rainbow", "Orange Rainbow", "Red Rainbow", "Black Rainbow", "Basketball", "Basketball Pink", "Basketball Red", "Basketball Gold", "Basketball Black", "First Card", "Wood", "Surge", "Flash Drop", "Doorbuster", "Cart Load", "Blackout", "Diamante"] },
      { name: "BASE CARDS I BLACKOUT VARIATION", type: "base", cardCount: 261, tiers: ["Base", "Rainbow Foilboard", "Foilfractor", "Holo Foil", "Sand Glitter", "Green", "Orange", "Victory", ["Gold", 2025], ["Platinum", 1], ["Black", 1], "Rainbow", "Blue Rainbow", "Green Rainbow", "Purple Rainbow", "Gold Rainbow", "Orange Rainbow", "Red Rainbow", "Black Rainbow", "Basketball", "Basketball Pink", "Basketball Red", "Basketball Gold", "Basketball Black", "First Card", "Wood", "Surge", "Flash Drop", "Doorbuster", "Cart Load", "Blackout", "Diamante"] },
      { name: "COMBO CARDS", type: "base", cardCount: 29, tiers: ["Base", "Rainbow Foilboard", "Foilfractor", "Holo Foil", "Sand Glitter", "Green", "Orange", "Victory", ["Gold", 2025], ["Platinum", 1], ["Black", 1], "Rainbow", "Blue Rainbow", "Green Rainbow", "Purple Rainbow", "Gold Rainbow", "Orange Rainbow", "Red Rainbow", "Black Rainbow", "Basketball", "Basketball Pink", "Basketball Red", "Basketball Gold", "Basketball Black", "First Card", "Wood", "Surge", "Flash Drop", "Doorbuster", "Cart Load", "Blackout", "Diamante"] },
      { name: "COMBO CARDS GOLDEN MIRROR IMAGE VARIATION", type: "base", cardCount: 29, tiers: ["Base", "Rainbow Foilboard", "Foilfractor", "Holo Foil", "Sand Glitter", "Green", "Orange", "Victory", ["Gold", 2025], ["Platinum", 1], ["Black", 1], "Rainbow", "Blue Rainbow", "Green Rainbow", "Purple Rainbow", "Gold Rainbow", "Orange Rainbow", "Red Rainbow", "Black Rainbow", "Basketball", "Basketball Pink", "Basketball Red", "Basketball Gold", "Basketball Black", "First Card", "Wood", "Surge", "Flash Drop", "Doorbuster", "Cart Load", "Blackout", "Diamante"] },
      { name: "COMBO CARDS BLACKOUT VARIATION", type: "base", cardCount: 29, tiers: ["Base", "Rainbow Foilboard", "Foilfractor", "Holo Foil", "Sand Glitter", "Green", "Orange", "Victory", ["Gold", 2025], ["Platinum", 1], ["Black", 1], "Rainbow", "Blue Rainbow", "Green Rainbow", "Purple Rainbow", "Gold Rainbow", "Orange Rainbow", "Red Rainbow", "Black Rainbow", "Basketball", "Basketball Pink", "Basketball Red", "Basketball Gold", "Basketball Black", "First Card", "Wood", "Surge", "Flash Drop", "Doorbuster", "Cart Load", "Blackout", "Diamante"] },
      { name: "THE DAILY DRIBBLE", type: "insert", cardCount: 39, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "NEW SCHOOL", type: "insert", cardCount: 39, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "1980 81 TOPPS CHROME BASKETBALL", type: "insert", cardCount: 0, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "LEVITATION", type: "insert", cardCount: 20, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "NO LIMIT", type: "insert", cardCount: 39, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "STARS OF THE NBA", type: "insert", cardCount: 29, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "RISE TO STARDOM", type: "insert", cardCount: 19, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "MVP VAULT", type: "insert", cardCount: 10, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "COMIC COURT", type: "insert", cardCount: 19, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "HOME COURT", type: "insert", cardCount: 10, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "SONIC BOOM", type: "insert", cardCount: 19, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "SOLE AMBITION", type: "insert", cardCount: 10, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "8 BIT BALLERS", type: "insert", cardCount: 39, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "GENERATION NOW", type: "insert", cardCount: 29, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "POWER PLAYERS", type: "insert", cardCount: 20, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "CLUTCH CITY PROSPECTS", type: "insert", cardCount: 9, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "BASE PLAYER NUMBER VARIATION", type: "insert", cardCount: 25, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "ALL KINGS", type: "insert", cardCount: 24, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "HARDWOOD STARS", type: "insert", cardCount: 19, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "COMPANION TOPPS CARDS", type: "insert", cardCount: 15, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "COMPANION TOPPS CARDS SHORT PRINTS", type: "insert", cardCount: 5, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "OVERSIZED TOPPS CARDS", type: "insert", cardCount: 15, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "OVERSIZED TOPPS CARDS SHORT PRINTS", type: "insert", cardCount: 5, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "SCAN AND SLAM", type: "insert", cardCount: 49, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "SOCIAL MEDIA FOLLOWBACK REDEMPTION", type: "insert", cardCount: 10, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "LIMITED STOCK LEGENDS", type: "insert", cardCount: 49, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "CLASS OF 25", type: "insert", cardCount: 19, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "BIG BOX BALLERS", type: "insert", cardCount: 49, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "1980 81 TOPPS BASKETBALL", type: "insert", cardCount: 94, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "FANATICS AUTHENTIC REDEMPTIONS", type: "insert", cardCount: 30, tiers: ["Base", "Foil", "Foilboard", ["Gold", 2025], ["Platinum", 1]] },
      { name: "FLAGSHIP REAL ONE AUTOGRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "1980 81 TOPPS BASKETBALL AUTOGRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "1980 81 TOPPS CHROME BASKETBALL VETERAN AUTOGRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "MARKS OF EXCELLENCE", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "CONTEMPORARY MARKS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "HAVOC MARKS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "TOPPS NOTCH SIGNATURES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "NEW APPLICANTS AUTOGRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "SIGNED AND SEALED", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "ROOKIE PHOTO SHOOT AUTOGRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "1980 81 TOPPS BASKETBALL ROOKIE AUTOGRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "FLAGSHIP REAL ONE ROOKIE AUTOGRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "1980 81 TOPPS BASKETBALL TRIPLE AUTOGRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "ROOKIE PHOTO SHOOT DUAL AUTOGRAPH", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "RETAIL RUSH SIGNATURES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "1980 81 TOPPS CHROME BASKETBALL ROOKIE AUTOGRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "SHOPPING SPREE SIGNATURES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "FLAGSHIP REAL ONE AUTOGRAPHS SPIKE LEE", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "RISE TO THE OCCASION RELICS", type: "relic", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Platinum", 1]] },
      { name: "OWN THE GAME", type: "relic", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Platinum", 1]] },
      { name: "ROOKIE ROUNDBALL REMNANTS", type: "relic", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Platinum", 1]] },
      { name: "FRANCHISE FABRICS", type: "relic", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Platinum", 1]] },
      { name: "SWISH AND STITCH RELICS", type: "relic", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Platinum", 1]] },
      { name: "WOVEN WONDERS RELICS", type: "relic", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Platinum", 1]] },
      { name: "FLAGSHIP REAL ONE RELIC", type: "relic", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Platinum", 1]] },
      { name: "STORE EXCLUSIVE RELICS", type: "relic", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Platinum", 1]] },
      { name: "RETAIL RIPPER RELICS", type: "relic", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Platinum", 1]] },
    ],
  },
  "Topps Chrome": {
    fullName: "2025-26 Topps Chrome",
    season: "2025-26",
    sortOrder: 1,
    subsets: [
      { name: "BASE CARDS", type: "base", cardCount: 290, tiers: ["Base", "Refractor", "Prism", "Negative", "Lightboard Logos", "Skylight", "X-Fractor", "Red/White/Blue", ["Magenta", 399], ["Teal", 299], "Wave", "RayWave", "Pulsar", "Basketball", "Image Variation", "1st Day Issue", ["Silver FDI", 12], ["Tri-Color FDI", 8], ["Yellow", 275], ["Aqua", 199], ["Blue", 150], ["Green", 99], ["Purple", 75], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["Frozenfractor", 5], ["SuperFractor", 1], ["Yellow Basketball", 275], ["Aqua Basketball", 199], ["Blue Basketball", 150], ["Green Basketball", 99], ["Purple Basketball", 75], ["Gold Basketball", 50], ["Orange Basketball", 25], ["Black Basketball", 10], ["Red Basketball", 5], ["Blue Wave", 150], ["Green Wave", 99], ["Purple Wave", 75], ["Gold Wave", 50], ["Orange Wave", 25], ["Black Wave", 10], ["Red Wave", 5], ["RayWave Yellow", 275], ["RayWave Aqua", 199], ["RayWave Blue", 150], ["RayWave Green", 99], ["RayWave Purple", 75], ["RayWave Gold", 50], ["RayWave Orange", 25], ["RayWave Black", 10], ["RayWave Red", 5], "Geometric Gold", "Geometric Orange", "Geometric Black", "Geometric Red", "Geometric White", ["Pulsar Purple", 75], ["Pulsar Gold", 50], ["Pulsar Orange", 25], ["Pulsar Black", 10], ["Pulsar Red", 5], "Sapphire", "Sapphire Purple", "Sapphire Gold", "Sapphire Orange", "Sapphire Black", "Sapphire Red", "Padparadscha"] },
      { name: "YOUTHQUAKE", type: "insert", cardCount: 14, tiers: ["Base", "Refractor", ["Yellow", 275], ["Aqua", 199], ["Blue", 150], ["Green", 99], ["Purple", 75], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "SLEEK FINISHERS", type: "insert", cardCount: 29, tiers: ["Base", "Refractor", ["Yellow", 275], ["Aqua", 199], ["Blue", 150], ["Green", 99], ["Purple", 75], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "DESTINY", type: "insert", cardCount: 24, tiers: ["Base", "Refractor", ["Yellow", 275], ["Aqua", 199], ["Blue", 150], ["Green", 99], ["Purple", 75], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "INSTINCT", type: "insert", cardCount: 19, tiers: ["Base", "Refractor", ["Yellow", 275], ["Aqua", 199], ["Blue", 150], ["Green", 99], ["Purple", 75], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "VOICES", type: "insert", cardCount: 9, tiers: ["Base", "Refractor", ["Yellow", 275], ["Aqua", 199], ["Blue", 150], ["Green", 99], ["Purple", 75], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "LOADING", type: "insert", cardCount: 15, tiers: ["Base", "Refractor", ["Yellow", 275], ["Aqua", 199], ["Blue", 150], ["Green", 99], ["Purple", 75], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "GENERATION RISING", type: "insert", cardCount: 19, tiers: ["Base", "Refractor", ["Yellow", 275], ["Aqua", 199], ["Blue", 150], ["Green", 99], ["Purple", 75], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "TALL TALES", type: "insert", cardCount: 25, tiers: ["Base", "Refractor", ["Yellow", 275], ["Aqua", 199], ["Blue", 150], ["Green", 99], ["Purple", 75], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "CLUTCH GENE", type: "insert", cardCount: 30, tiers: ["Base", "Refractor", ["Yellow", 275], ["Aqua", 199], ["Blue", 150], ["Green", 99], ["Purple", 75], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "XS AND WHOAS", type: "insert", cardCount: 10, tiers: ["Base", "Refractor", ["Yellow", 275], ["Aqua", 199], ["Blue", 150], ["Green", 99], ["Purple", 75], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "ROCK STARS", type: "insert", cardCount: 19, tiers: ["Base", ["SuperFractor", 1]] },
      { name: "LETS GO", type: "insert", cardCount: 14, tiers: ["Base", ["SuperFractor", 1]] },
      { name: "ULTRA VIOLET", type: "insert", cardCount: 14, tiers: ["Base", ["SuperFractor", 1]] },
      { name: "RADIATING ROOKIES", type: "insert", cardCount: 9, tiers: ["Base", ["SuperFractor", 1]] },
      { name: "HELIX", type: "insert", cardCount: 19, tiers: ["Base", ["SuperFractor", 1]] },
      { name: "SAPPHIRE SELECTIONS", type: "insert", cardCount: 19, tiers: ["Base", "Refractor", ["Yellow", 275], ["Aqua", 199], ["Blue", 150], ["Green", 99], ["Purple", 75], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "INFINITE SAPPHIRE", type: "insert", cardCount: 19, tiers: ["Base", "Refractor", ["Yellow", 275], ["Aqua", 199], ["Blue", 150], ["Green", 99], ["Purple", 75], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "GO TIME", type: "insert", cardCount: 24, tiers: ["Base", "Refractor", ["Yellow", 275], ["Aqua", 199], ["Blue", 150], ["Green", 99], ["Purple", 75], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "BALL OF DUTY", type: "insert", cardCount: 25, tiers: ["Base", "Refractor", ["Yellow", 275], ["Aqua", 199], ["Blue", 150], ["Green", 99], ["Purple", 75], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "INSPIRATIONAL", type: "insert", cardCount: 20, tiers: ["Base", "Refractor", ["Yellow", 275], ["Aqua", 199], ["Blue", 150], ["Green", 99], ["Purple", 75], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "ACTIVATORS", type: "insert", cardCount: 14, tiers: ["Base", "Refractor", ["Yellow", 275], ["Aqua", 199], ["Blue", 150], ["Green", 99], ["Purple", 75], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "SERENITY", type: "insert", cardCount: 14, tiers: ["Base", "Refractor", ["Yellow", 275], ["Aqua", 199], ["Blue", 150], ["Green", 99], ["Purple", 75], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "ADVISORY", type: "insert", cardCount: 19, tiers: ["Base", ["SuperFractor", 1]] },
      { name: "GLASS CANVAS", type: "insert", cardCount: 20, tiers: ["Base", ["SuperFractor", 1]] },
      { name: "PARADOX", type: "insert", cardCount: 29, tiers: ["Base", ["SuperFractor", 1]] },
      { name: "PATENTED", type: "insert", cardCount: 29, tiers: ["Base", ["SuperFractor", 1]] },
      { name: "FANATICAL", type: "insert", cardCount: 24, tiers: ["Base", ["SuperFractor", 1]] },
      { name: "BASE CARD VARIATIONS", type: "insert", cardCount: 49, tiers: ["Base", ["SuperFractor", 1]] },
      { name: "FINALS", type: "insert", cardCount: 10, tiers: ["Base", ["SuperFractor", 1]] },
      { name: "TOPPS CHROME AUTOGRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "TOPPS CHROME AUTOGRAPHS ROOKIES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "SKY WRITE SIGNATURES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "TOPPS AUTOGRAPH ISSUE ROOKIES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "NEXT STOP SIGNATURES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "SIGNATURE STYLE", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "TOPPS AUTOGRAPH ISSUE", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "FUTURE STARS AUTOGRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "CHROMOGRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "CHROMOGRAPHS ROOKIE", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "STRATOSPHERIC SIGNATURES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "STRATOSPHERIC SIGNATURES ROOKIES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "TOPPS CHROME AUTOGRAPHS II", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "TOPPS CHROME GOLD LOGOMAN", type: "relic", cardCount: 3, tiers: ["Base", ["Gold", 25], ["SuperFractor", 1]] },
      { name: "TOPPS CHROME GOLD LOGOMAN RELICS REDEMPTION CARD", type: "relic", cardCount: 3, tiers: ["Base", ["Gold", 25], ["SuperFractor", 1]] },
      { name: "TOPPS CHROME GOLD LOGOMAN II", type: "autograph_relic", cardCount: 3, tiers: ["Base", ["Gold", 25], ["SuperFractor", 1]] },
      { name: "TOPPS CHROME GOLD LOGOMAN II AUTOGRAPH RELICS REDEMPTION CARD", type: "autograph_relic", cardCount: 3, tiers: ["Base", ["Gold", 25], ["SuperFractor", 1]] },
    ],
  },
  "Topps Chrome Sapphire": {
    fullName: "2025-26 Topps Chrome Sapphire",
    season: "2025-26",
    sortOrder: 2,
    subsets: [
      { name: "BASE CARDS I", type: "base", cardCount: 96, tiers: ["Base", ["Gold Sapphire", 50], ["Orange Sapphire", 25], ["Purple Sapphire", 15], ["Black Sapphire", 10], ["Red Sapphire", 5], ["Padparadscha Sapphire", 1]] },
      { name: "BASE CARDS II", type: "base", cardCount: 97, tiers: ["Base", ["Gold Sapphire", 50], ["Orange Sapphire", 25], ["Purple Sapphire", 15], ["Black Sapphire", 10], ["Red Sapphire", 5], ["Padparadscha Sapphire", 1]] },
      { name: "BASE CARDS III", type: "base", cardCount: 98, tiers: ["Base", ["Gold Sapphire", 50], ["Orange Sapphire", 25], ["Purple Sapphire", 15], ["Black Sapphire", 10], ["Red Sapphire", 5], ["Padparadscha Sapphire", 1]] },
      { name: "SAPPHIRE SELECTIONS", type: "insert", cardCount: 19, tiers: ["Base", ["Gold Sapphire", 50], ["Red Sapphire", 5], ["SuperFractor", 1]] },
      { name: "INFINITE SAPPHIRE", type: "insert", cardCount: 19, tiers: ["Base", ["Gold Sapphire", 50], ["Red Sapphire", 5], ["SuperFractor", 1]] },
      { name: "TOPPS CHROME AUTOGRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "TOPPS CHROME AUTOGRAPHS ROOKIES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "SKY WRITE SIGNATURES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "TOPPS AUTOGRAPH ISSUE ROOKIES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "NEXT STOP SIGNATURES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "SIGNATURE STYLE", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "TOPPS CHROME AUTOGRAPHS II", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
    ],
  },
  "Topps Finest": {
    fullName: "2025-26 Topps Finest",
    season: "2025-26",
    sortOrder: 3,
    subsets: [
      { name: "BASE COMMON", type: "base", cardCount: 97, tiers: ["Base", "Refractor", ["Green", 99], ["Blue", 75], ["Purple", 50], ["Gold", 25], ["Orange", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "BASE UNCOMMON", type: "base", cardCount: 99, tiers: ["Base", "Refractor", ["Green", 99], ["Blue", 75], ["Purple", 50], ["Gold", 25], ["Orange", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "BASE RARE", type: "base", cardCount: 97, tiers: ["Base", "Refractor", ["Green", 99], ["Blue", 75], ["Purple", 50], ["Gold", 25], ["Orange", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "ARRIVALS", type: "insert", cardCount: 29, tiers: ["Base", "Refractor", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "FIRST", type: "insert", cardCount: 29, tiers: ["Base", "Refractor", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "FINISHERS", type: "insert", cardCount: 9, tiers: ["Base", "Refractor", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "PULSE", type: "insert", cardCount: 19, tiers: ["Base", "Refractor", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "THE MAN", type: "insert", cardCount: 19, tiers: ["Base", "Refractor", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "HEADLINERS", type: "insert", cardCount: 14, tiers: ["Base", "Refractor", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "MUSE", type: "insert", cardCount: 30, tiers: ["Base", "Refractor", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "AURA", type: "insert", cardCount: 19, tiers: ["Base", "Refractor", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "AUTOGRAPH CARDS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "ROOKIE AUTOGRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "BASELINE AUTOGRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "MASTERS AUTOGRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "ELECTRIFYING SIGNATURES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "COLOSSAL SHOTS AUTOGRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
    ],
  },
  "Topps Holiday": {
    fullName: "2025-26 Topps Holiday",
    season: "2025-26",
    sortOrder: 4,
    subsets: [
      { name: "BASE CARDS I", type: "base", cardCount: 195, tiers: ["Base", "Metallic Snowflake", "Festive", ["Winter Wonderland", 199], ["Ornament", 99], ["Gold Gift", 50], ["Red Velvet", 25], ["SuperFractor", 1]] },
      { name: "BASE HOLIDAY VARIATION SUPER SHORT PRINTS", type: "insert", cardCount: 0, tiers: ["Base", ["Gold", 50], ["SuperFractor", 1]] },
      { name: "BASE HOLIDAY BACKS VARIATION SUPER SHORT PRINTS", type: "insert", cardCount: 0, tiers: ["Base", ["Gold", 50], ["SuperFractor", 1]] },
      { name: "FROSTBITE FINISHERS", type: "insert", cardCount: 0, tiers: ["Base", ["Gold", 50], ["SuperFractor", 1]] },
      { name: "HIDDEN ELF", type: "insert", cardCount: 0, tiers: ["Base", ["Gold", 50], ["SuperFractor", 1]] },
      { name: "MAKING THE NICE LIST", type: "insert", cardCount: 24, tiers: ["Base", ["Gold", 50], ["SuperFractor", 1]] },
      { name: "EVERGREEN", type: "insert", cardCount: 0, tiers: ["Base", ["Gold", 50], ["SuperFractor", 1]] },
      { name: "OVERSIZED DIE CUT ORNAMENT", type: "insert", cardCount: 0, tiers: ["Base", ["Gold", 50], ["SuperFractor", 1]] },
      { name: "PLAYER RELICS", type: "relic", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "DUAL PLAYER RELICS", type: "relic", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "PLAYER HOLIDAY SHAPED RELICS", type: "relic", cardCount: 24, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "HOLIDAY RELICS", type: "relic", cardCount: 40, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "BASE CARDS I AUTOGRAPH PARALLEL", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "BASE CARDS II AUTOGRAPH PARALLEL", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
    ],
  },
  "Topps Midnight": {
    fullName: "2025-26 Topps Midnight",
    season: "2025-26",
    sortOrder: 5,
    subsets: [
      { name: "BASE CARDS", type: "base", cardCount: 98, tiers: ["Base", "Twilight", "Midnight Glow", ["Blue", 199], ["Purple", 150], ["Gold", 99], ["Orange", 50], ["Red", 25], ["Black", 10], ["SuperFractor", 1]] },
      { name: "ROOKIE JERSEY AUTOGRAPHS", type: "autograph_relic", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "STROKE OF MIDNIGHT AUTOGRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "STROKE OF MIDNIGHT AUTOGRAPHS ROOKIES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "ROOKIE HORIZON SIGNATURES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "MIDNIGHT SUN SIGNATURES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "MIDNIGHT SUN SIGNATURES ROOKIES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "DARK MARKS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "DARK MARKS ROOKIES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "DARK MATTER AUTOGRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "DARK MATTER AUTOGRAPHS ROOKIES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "MIDNIGHT OIL MARKS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "MIDNIGHT OIL MARKS ROOKIES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "STROKE OF MIDNIGHT AUTOGRAPHS II", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "NIGHT OWLS", type: "insert", cardCount: 24, tiers: ["Base", ["Gold", 99], ["Orange", 50], ["Red", 25], ["Black", 10], ["SuperFractor", 1]] },
      { name: "DAYDREAMERS", type: "insert", cardCount: 20, tiers: ["Base", ["Gold", 99], ["Orange", 50], ["Red", 25], ["Black", 10], ["SuperFractor", 1]] },
      { name: "INSOMNIA", type: "insert", cardCount: 25, tiers: ["Base", ["Gold", 99], ["Orange", 50], ["Red", 25], ["Black", 10], ["SuperFractor", 1]] },
      { name: "MOONFALL", type: "insert", cardCount: 30, tiers: ["Base", ["Gold", 99], ["Orange", 50], ["Red", 25], ["Black", 10], ["SuperFractor", 1]] },
      { name: "NIGHT SHADE", type: "insert", cardCount: 29, tiers: ["Base", ["Gold", 99], ["Orange", 50], ["Red", 25], ["Black", 10], ["SuperFractor", 1]] },
      { name: "DREAMLAND", type: "insert", cardCount: 29, tiers: ["Base", ["Gold", 99], ["Orange", 50], ["Red", 25], ["Black", 10], ["SuperFractor", 1]] },
      { name: "NIGHT VISION", type: "insert", cardCount: 25, tiers: ["Base", ["Gold", 99], ["Orange", 50], ["Red", 25], ["Black", 10], ["SuperFractor", 1]] },
      { name: "TWILIGHT", type: "insert", cardCount: 15, tiers: ["Base", ["Gold", 99], ["Orange", 50], ["Red", 25], ["Black", 10], ["SuperFractor", 1]] },
    ],
  },
  "Topps Three": {
    fullName: "2025-26 Topps Three",
    season: "2025-26",
    sortOrder: 6,
    subsets: [
      { name: "BASE CARDS", type: "base", cardCount: 99, tiers: ["Base", ["Blue", 199], ["Green", 150], ["Purple", 99], ["Gold", 50], ["Orange", 25], ["Red", 10], ["Black", 5], ["SuperFractor", 1]] },
      { name: "ICE WATER", type: "insert", cardCount: 39, tiers: ["Base", ["Gold", 50], ["Red", 10], ["SuperFractor", 1]] },
      { name: "FLIGHT PATH", type: "insert", cardCount: 29, tiers: ["Base", ["Gold", 50], ["Red", 10], ["SuperFractor", 1]] },
      { name: "ARCHITECTS", type: "insert", cardCount: 29, tiers: ["Base", ["Gold", 50], ["Red", 10], ["SuperFractor", 1]] },
      { name: "3 AND D", type: "insert", cardCount: 39, tiers: ["Base", ["Gold", 50], ["Red", 10], ["SuperFractor", 1]] },
      { name: "MONSTERS OF THE DEEP", type: "insert", cardCount: 29, tiers: ["Base", ["Gold", 50], ["Red", 10], ["SuperFractor", 1]] },
      { name: "THE PAINT", type: "insert", cardCount: 29, tiers: ["Base", ["Gold", 50], ["Red", 10], ["SuperFractor", 1]] },
      { name: "ROOKIE 3 PATCH AUTOGRAPHS HORIZONTAL", type: "autograph_relic", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "ROOKIE 3 PATCH AUTOGRAPHS VERTICAL", type: "autograph_relic", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "RELICS AUTOGRAPHS PRIME", type: "autograph_relic", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "TRIPLE RELICS AUTOGRAPHS", type: "autograph_relic", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "ROOKIE RELICS AUTOGRAPHS", type: "autograph_relic", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "VETERAN 3 PATCH AUTOGRAPHS", type: "autograph_relic", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "FRESH FORCE RELIC AUTOGRAPHS", type: "autograph_relic", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "RAINDROPS SIGNATURES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "SERENDIPITOUS SIGS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "REMARKABLE", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "FULL COURT SIGNS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "HIT THE MARK", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "TRIPLE POWER AUTOGRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "ROOKIE AUTOGRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "THUNDERDUNK SIGNATURES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "ROOKIEVERSE AUTOGRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "RIM REAPERS SIGNATURES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "QUEST FOR GLORY AUTOGRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "CITY DRIP SIGNATURES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "NEXT FEATURE SIGNATURES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "GAME TIME GRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
    ],
  },
  "Topps Cosmic Chrome": {
    fullName: "2025-26 Topps Cosmic Chrome",
    season: "2025-26",
    sortOrder: 7,
    subsets: [
      { name: "BASE CARDS", type: "base", cardCount: 97, tiers: ["Base", "Refractor", "Nucleus", "Aqua Equinox", "Purple Nebula", "Blue Moon", ["Green Space Dust", 99], "Gold Interstellar", "Orange Galactic", "Black Eclipse", "Red Flare", ["SuperFractor", 1], "White Hole FDI", "Lunar FDI"] },
      { name: "BASE CARDS II", type: "base", cardCount: 99, tiers: ["Base", "Refractor", "Nucleus", "Aqua Equinox", "Purple Nebula", "Blue Moon", ["Green Space Dust", 99], "Gold Interstellar", "Orange Galactic", "Black Eclipse", "Red Flare", ["SuperFractor", 1], "White Hole FDI", "Lunar FDI"] },
      { name: "GALAXY GREATS", type: "insert", cardCount: 35, tiers: ["Base", "Refractor", ["Green", 99], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "EXTRATERRESTRIAL TALENT", type: "insert", cardCount: 24, tiers: ["Base", "Refractor", ["Green", 99], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "PROPULSION", type: "insert", cardCount: 24, tiers: ["Base", "Refractor", ["Green", 99], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "SPACE WALK", type: "insert", cardCount: 14, tiers: ["Base", "Refractor", ["Green", 99], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "STARFRACTOR", type: "insert", cardCount: 49, tiers: ["Base", "Refractor", ["Green", 99], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "RE ENTRY", type: "insert", cardCount: 39, tiers: ["Base", "Refractor", ["Green", 99], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "GEOCENTRIC", type: "insert", cardCount: 30, tiers: ["Base", "Refractor", ["Green", 99], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "FIRST LIGHT", type: "insert", cardCount: 29, tiers: ["Base", "Refractor", ["Green", 99], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "HYPER NOVA", type: "insert", cardCount: 19, tiers: ["Base", "Refractor", ["Green", 99], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "COSMIC DUST", type: "insert", cardCount: 19, tiers: ["Base", "Refractor", ["Green", 99], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "PLANETARY PURSUIT", type: "insert", cardCount: 100, tiers: ["Base", "Refractor", ["Green", 99], ["Gold", 50], ["Orange", 25], ["Black", 10], ["Red", 5], ["SuperFractor", 1]] },
      { name: "COSMIC CHROME AUTOGRAPH VARIATION", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "SINGULARITY SIGNATURES", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "ALIEN AUTOGRAPHS", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "ELECTRO STATIC SIGNATURES REFRACTOR", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "FIRST FLIGHT SIGNATURES REFRACTOR", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
      { name: "COSMIC CHROME AUTOGRAPH VARIATION II", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
    ],
  },
  "Topps Cactus Jack": {
    fullName: "2025-26 Topps Cactus Jack",
    season: "2025-26",
    sortOrder: 8,
    subsets: [
      { name: "ASG CARDS", type: "base", cardCount: 97, tiers: ["Base", ["Orange Refractor", 50], ["Laser Refractor", 25], ["Black Refractor", 10], ["Red Refractor", 5], ["SuperFractor", 1]] },
      { name: "SICKO STARS", type: "insert", cardCount: 25, tiers: ["Base", ["SuperFractor", 1]] },
      { name: "ALL STAR GAME AUTOGRAPH VARIATION", type: "autograph", cardCount: 0, tiers: ["Base", ["Gold", 25], ["Red", 5], ["SuperFractor", 1]] },
    ],
  },
};